### ISSUE TITLE
Is OMEVisual still included in Fiji?

### ISSUE THREAD

**Issue by jsbtic** [fiji/OMEVisual#4]
I wonder how can the OMEVisual be launched in Fiji? According to the [manual](https://imagej.net/plugins/omevisual), the pluging is accessible from _Plugins › Utilities › Visualize OME Metadata_ but apparently at least in current version ( (Fiji is Just) Imagej 2.14.0; Java 1.8.0_322  [64bit]) of FIJI it's missing:

![fiji_utilities_screenshot](https://github.com/user-attachments/assets/afea8d6c-858a-475a-9a89-9ceb7ad8a282)

On the other hand the `OMEVisual-2.0.0.jar` is included in the `Fiji.app/jars` -folder. 

I would be grateful for any solutions/verification of the issue.

My best

**Comment by ctrueden** [comment]
@jsbtic The command is still there... in the *first* Utilities menu toward the very top of the Plugins menu. :face_exhaling: 

This bug with two submenus of the same name has been an issue for a long time; see fiji/fiji#144. It's on the list of issues to clean up as part of the [Fiji Fit project](https://github.com/orgs/fiji/projects/1) to improve Fiji's quality-of-life.

**Comment by jsbtic** [comment]
Much obliged @ctrueden, and apologies (I feel embarrassed 🙈)

**Comment by ctrueden** [comment]
No worries @jsbtic—the fact that there are two submenus with the same name is super confusing! :sweat_smile:
